### ISSUE TITLE
database locked error on infra events

### ISSUE THREAD

**Issue by octavimar** [qwebsolutions/mds#1]
Randomly (cannot figure how to repro this at the moment) these events are raised by infra:

Event timestamp
9/5/2024, 11:04:27
Event description
Internal error
Event source
Production-1
Details
code = Busy (5), message = System.Data.SQLite.SQLiteException (0x87AF00AA): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteTransaction.Begin(Boolean deferredLock)
   at System.Data.SQLite.SQLiteConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at System.Data.SQLite.SQLiteConnection.BeginTransaction()
   at Metapsi.Sqlite.Db.WithCommit(String filePath, Func`2 dbAction) in /home/calin/github.com/metapsi/Metapsi.Sqlite/LoadIRecords.cs:line 76
   at MdsInfrastructure.Db.StoreHealthStatus(String fullDbPath, MachineStatus healthStatus) in /home/calin/github.com/mds/MdsInfrastructure.Db/Db.cs:line 497
   at Metapsi.ApiHandler.<>c__DisplayClass2_0`1.<<MapCommand>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass90_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware.InvokeInternal(HttpContext context)
   at Metapsi.WebServer.<>c__DisplayClass10_0.<<AddWebServer>b__6>d.MoveNext()
--- End of stack trace from previous location ---
   at Metapsi.WebServer.<>c.<<AddWebServer>b__10_5>d.MoveNext()
--- End of stack trace from previous location ---
   at Metapsi.WebServer.<>c__DisplayClass10_0.<<AddWebServer>b__4>d.MoveNext()
--- End of stack trace from previous location ---
   at Metapsi.WebServer.<>c__DisplayClass10_0.<<AddWebServer>b__3>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.

**Comment by calin-dobos** [comment]
Should be fixed in v0.5.4
